# Generated by Django 5.0.6 on 2024-05-16 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College_Management_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionyearmodel',
            name='label',
            field=models.CharField(default='Default Label', max_length=255),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='session_year_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='College_Management_app.sessionyearmodel'),
        ),
        migrations.AlterField(
            model_name='students',
            name='session_year_id',
            field=models.ForeignKey(default=1999, on_delete=django.db.models.deletion.CASCADE, to='College_Management_app.sessionyearmodel'),
            preserve_default=False,
        ),
    ]
