# Generated by Django 5.0.6 on 2024-05-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College_Management_app', '0002_sessionyearmodel_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionyearmodel',
            name='label',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
